// Ready-made decks for common high school and clinical-skills topics.
// Adding one copies it into her decks, where she can edit it like any other.
// Vital-sign values are standard adult reference ranges (AHA and common
// nursing-assistant curricula); the deck says to follow the instructor.

const deck = (id, subject, name, note, pairs, ordered = false) => ({ id, subject, name, note, ordered, cards: pairs.map(([term, definition]) => ({ term, definition })) });

export const STARTERS = [
  deck("med-terms", "clinical", "Medical terminology: prefixes and suffixes", "Word parts you'll see in charts and doctors' notes.", [
    ["brady-", "slow"],
    ["tachy-", "fast"],
    ["hyper-", "above normal, excessive"],
    ["hypo-", "below normal, deficient"],
    ["a- / an-", "without, absence of"],
    ["dys-", "difficult, painful, or abnormal"],
    ["peri-", "around"],
    ["endo-", "within, inside"],
    ["-itis", "inflammation"],
    ["-ectomy", "surgical removal"],
    ["-otomy", "cutting into, incision"],
    ["-ostomy", "surgically creating an opening"],
    ["-algia", "pain"],
    ["-emia", "blood condition"],
    ["-ology", "study of"],
    ["-scopy", "visual examination with an instrument"],
    ["-megaly", "enlargement"],
    ["-pnea", "breathing"],
    ["-cyte", "cell"],
    ["cardi/o", "heart"],
    ["hepat/o", "liver"],
    ["nephr/o", "kidney"],
    ["gastr/o", "stomach"],
    ["derm/o, dermat/o", "skin"],
    ["oste/o", "bone"],
    ["neur/o", "nerve"],
    ["pulmon/o", "lung"],
    ["hem/o, hemat/o", "blood"],
    ["erythr/o", "red"],
    ["leuk/o", "white"],
    ["cyan/o", "blue"],
  ]),
  deck("vital-signs", "clinical", "Vital signs (adult)", "Typical adult reference ranges. Always follow your instructor and clinical site.", [
    ["Normal adult resting heart rate", "60–100 beats per minute"],
    ["Normal adult respiratory rate", "12–20 breaths per minute"],
    ["Normal adult blood pressure", "Less than 120/80 mmHg"],
    ["Normal oxygen saturation (SpO2)", "95–100%"],
    ["Average normal body temperature", "About 98.6 °F (37 °C); normal is roughly 97–99 °F"],
    ["Fever", "A temperature of 100.4 °F (38 °C) or higher"],
    ["Bradycardia", "Adult heart rate below 60 beats per minute"],
    ["Tachycardia", "Adult heart rate above 100 beats per minute"],
    ["Stage 1 hypertension", "Systolic 130–139 or diastolic 80–89 mmHg"],
    ["Systolic pressure", "The top number: pressure in the arteries when the heart beats"],
    ["Diastolic pressure", "The bottom number: pressure in the arteries when the heart rests between beats"],
    ["Radial pulse", "Pulse taken at the wrist, on the thumb side"],
    ["Carotid pulse", "Pulse taken on the side of the neck"],
    ["Apical pulse", "Heartbeat heard with a stethoscope over the apex of the heart, on the left side of the chest"],
    ["Sphygmomanometer", "The blood pressure cuff and gauge"],
    ["Pulse oximeter", "Clips on a finger to measure oxygen saturation and pulse"],
  ]),
  deck(
    "handwashing",
    "clinical",
    "Handwashing steps",
    "A common skills-checklist order. Follow your program's checklist if it differs.",
    [
      ["Turn on the water and adjust it to a comfortable warm temperature", "Use a clean paper towel if the faucet has hand controls, per your program"],
      ["Wet hands and wrists, keeping fingertips pointed down", "Hands lower than elbows so water runs off the fingertips"],
      ["Apply soap", "Enough to cover all hand surfaces"],
      ["Lather and scrub all surfaces for at least 20 seconds", "Palms, backs, between fingers, thumbs, and wrists, using friction"],
      ["Clean under the fingernails", "Rub nails against the opposite palm or use a nail brush"],
      ["Rinse from wrists to fingertips, fingertips pointed down", "Don't touch the inside of the sink"],
      ["Dry hands with a clean paper towel", "From fingertips to wrists"],
      ["Turn off the faucet with a clean, dry paper towel", "Keeps clean hands off the dirty faucet"],
      ["Throw the paper towel away", "Without touching the trash can"],
    ],
    true,
  ),
  deck("cell-parts", "biology", "Cell parts and what they do", "Organelles for cell biology units.", [
    ["Nucleus", "Holds the cell's DNA and controls the cell's activities"],
    ["Nucleolus", "Inside the nucleus; makes ribosomes"],
    ["Mitochondria", "Release energy (ATP) from food through cellular respiration"],
    ["Ribosome", "Makes proteins"],
    ["Rough endoplasmic reticulum", "Studded with ribosomes; makes and moves proteins"],
    ["Smooth endoplasmic reticulum", "Makes lipids and breaks down some toxins"],
    ["Golgi apparatus", "Modifies, sorts, and packages proteins to ship out"],
    ["Lysosome", "Breaks down waste and worn-out parts with enzymes"],
    ["Cell membrane", "Controls what enters and leaves the cell"],
    ["Cell wall", "Rigid outer layer in plants, fungi, and bacteria that supports the cell"],
    ["Chloroplast", "Carries out photosynthesis in plant cells"],
    ["Vacuole", "Stores water, nutrients, and waste; large and central in plant cells"],
    ["Cytoplasm", "Gel-like fluid that fills the cell and holds the organelles"],
    ["Cytoskeleton", "Network of protein fibers that gives the cell its shape and helps it move"],
    ["Prokaryote", "A cell with no nucleus, such as bacteria"],
    ["Eukaryote", "A cell with a nucleus and membrane-bound organelles"],
  ]),
  deck("spanish-greetings", "spanish", "Spanish: greetings and everyday phrases", "Basics for first-year Spanish.", [
    ["hola", "hello"],
    ["adiós", "goodbye"],
    ["hasta luego", "see you later"],
    ["buenos días", "good morning"],
    ["buenas tardes", "good afternoon"],
    ["buenas noches", "good evening / good night"],
    ["¿Cómo estás?", "How are you? (informal)"],
    ["¿Cómo está usted?", "How are you? (formal)"],
    ["Me llamo…", "My name is…"],
    ["¿Cómo te llamas?", "What's your name? (informal)"],
    ["mucho gusto", "nice to meet you"],
    ["por favor", "please"],
    ["gracias", "thank you"],
    ["de nada", "you're welcome"],
    ["lo siento", "I'm sorry"],
    ["perdón", "excuse me / pardon"],
    ["¿Qué hora es?", "What time is it?"],
    ["¿Dónde está el baño?", "Where is the bathroom?"],
    ["No entiendo.", "I don't understand."],
    ["¿Cómo se dice…?", "How do you say…?"],
  ]),
  deck("us-government", "history", "U.S. government basics", "Civics and U.S. history foundations.", [
    ["Legislative branch", "Congress (Senate and House of Representatives); makes laws"],
    ["Executive branch", "The President and federal agencies; carries out and enforces laws"],
    ["Judicial branch", "The Supreme Court and federal courts; interprets laws"],
    ["Checks and balances", "Each branch can limit the powers of the other two"],
    ["Separation of powers", "Government power is divided among three branches"],
    ["Federalism", "Power is shared between the national government and the states"],
    ["Declaration of Independence", "Adopted July 4, 1776; announced the colonies' independence from Britain"],
    ["U.S. Constitution", "Written in 1787; the supreme law of the United States"],
    ["Bill of Rights", "The first 10 amendments to the Constitution"],
    ["First Amendment", "Protects freedom of religion, speech, press, assembly, and petition"],
    ["Veto", "The President's power to reject a bill passed by Congress"],
    ["Number of U.S. senators", "100 (two from each state)"],
    ["Number of voting members of the House", "435"],
    ["Judicial review", "The courts' power to strike down laws that violate the Constitution"],
  ]),
  deck(
    "us-timeline",
    "history",
    "U.S. history timeline",
    "Key events in order. Practice them with Steps.",
    [
      ["Declaration of Independence", "1776"],
      ["U.S. Constitution written", "1787"],
      ["Louisiana Purchase", "1803"],
      ["Civil War begins", "1861"],
      ["Emancipation Proclamation", "1863"],
      ["19th Amendment gives women the right to vote", "1920"],
      ["Stock market crash starts the Great Depression", "1929"],
      ["Attack on Pearl Harbor; U.S. enters World War II", "1941"],
      ["Brown v. Board of Education", "1954"],
      ["Civil Rights Act", "1964"],
      ["Apollo 11 Moon landing", "1969"],
    ],
    true,
  ),
  deck("literary-terms", "english", "Literary terms", "For English class reading and essays.", [
    ["Simile", "A comparison using \"like\" or \"as\""],
    ["Metaphor", "A comparison that says one thing is another, without \"like\" or \"as\""],
    ["Personification", "Giving human qualities to something that isn't human"],
    ["Hyperbole", "Deliberate exaggeration for effect"],
    ["Alliteration", "Repeating the same starting sound in nearby words"],
    ["Onomatopoeia", "A word that imitates a sound, like \"buzz\""],
    ["Imagery", "Language that appeals to the five senses"],
    ["Symbolism", "Using an object or idea to stand for something larger"],
    ["Foreshadowing", "Hints about what will happen later in the story"],
    ["Irony", "A contrast between what is expected and what actually happens"],
    ["Theme", "The central message or insight about life in a work"],
    ["Protagonist", "The main character"],
    ["Antagonist", "The character or force that opposes the main character"],
    ["Tone", "The author's attitude toward the subject"],
    ["Mood", "The feeling the reader gets from the work"],
    ["Point of view", "Who is telling the story (first, second, or third person)"],
  ]),
  deck("geometry-formulas", "geometry", "Geometry formulas", "Area, volume, and coordinate geometry.", [
    ["Area of a rectangle", "length × width"],
    ["Area of a triangle", "½ × base × height"],
    ["Area of a parallelogram", "base × height"],
    ["Area of a trapezoid", "½ × (base₁ + base₂) × height"],
    ["Area of a circle", "π × r²"],
    ["Circumference of a circle", "2 × π × r (or π × d)"],
    ["Pythagorean theorem", "a² + b² = c² (for a right triangle, c is the hypotenuse)"],
    ["Sum of the angles in a triangle", "180°"],
    ["Sum of the interior angles of a polygon with n sides", "(n − 2) × 180°"],
    ["Complementary angles", "Two angles that add up to 90°"],
    ["Supplementary angles", "Two angles that add up to 180°"],
    ["Vertical angles", "Opposite angles formed by two intersecting lines; they are equal"],
    ["Volume of a rectangular prism", "length × width × height"],
    ["Volume of a cylinder", "π × r² × h"],
    ["Volume of a sphere", "⁴⁄₃ × π × r³"],
    ["Slope of a line", "(y₂ − y₁) ÷ (x₂ − x₁)"],
    ["Distance formula", "√((x₂ − x₁)² + (y₂ − y₁)²)"],
    ["Midpoint formula", "((x₁ + x₂) ÷ 2, (y₁ + y₂) ÷ 2)"],
  ]),
];
